config/routes.rb
Rails.application.routes.draw do
  
  resources :contactos
  devise_for :users
  
  root 'pages#index' #get 'pages/index'

  get 'pages/about_us'

  get 'pages/faq'

  get 'pages/tos'

  get 'pages/contact_us'

  get 'spaces/list/:id/' => "spaces#list"
  
  get 'reservations/thank_you_page'
  
  get 'pages/gracias'
  
  get 'pages/busqueda'
  
  
  resources :profiles
  
  resources :ub_countries
  
  resources :ub_departments
  
  resources :ub_provinces
  
  resources :profile_phones
  
  resources :spaces
  
  resources :reservations
  
  get "/deparments/:country/" => "ub_departments#show"
  
  get "/provinces/:department/" => "ub_provinces#showProvinces"
  
  get "/districts/:department/:province/" => "ub_districts#showDistricts"
  
  get "/districts/:department/:province/" => "ub_districts#showDistricts"
  

end

app/models/car.rb
class Car < ActiveRecord::Base
end

app/models/car_type.rb
class CarType < ActiveRecord::Base
end

app/models/contacto.rb
class Contacto < ActiveRecord::Base
    
    validates :nombre, presence: {message: "El campo no puede quedar vacio .."}
    validates :correo, format: { with: /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i, message: "Correo no válido" }
    validates :mensaje, presence: {message: "El campo no puede quedar vacio .."}

end

app/models/phone_type.rb
class PhoneType < ActiveRecord::Base
    
    # El Tipo de teléfono tiene de uno a muchos números de telefonos
    has_many :profile_phones
    
end

app/models/profile.rb
class Profile < ActiveRecord::Base
    
    # Un Perfil pertenece a un usuario
    belongs_to :user
    
    # Perfil tiene de uno a muchos numeros telefónicos
    has_many :profile_phones

    # Un País pertenece a un Perfil
    belongs_to :ub_country
    
    # Un Departamento pertenece a un Perfil
    belongs_to :ub_department
    
    # Una Provincia pertenece a un Perfil
    belongs_to :ub_province
    
    # Un Distrito pertenece a un Perfil
    belongs_to :ub_district
    
    # Utilizando atributos de otros modelos
    accepts_nested_attributes_for :profile_phones
    accepts_nested_attributes_for :ub_department
    accepts_nested_attributes_for :ub_province
    accepts_nested_attributes_for :ub_district
    
    #validates :nombres, presence: { message: "El nombre es obligatorio" }
    #validates :ap_paterno, presence: { message: "El Apellido Paterno es obligatorio" }
    #validates :ap_materno, presence: { message: "El Apellido Materno es obligatorio" }
    #validates :descripcion,  presence: { message: "Es es obligatorio ingresar un descripción" }
    #validates :direccion,  presence: { message: "Es es obligatorio indicar una dirección" }

end

app/models/profile_phone.rb
class ProfilePhone < ActiveRecord::Base
    
    # El teléfono pertenece a un Perfil
    belongs_to :profile 
    
    # El Tipo de teléfono pertenece a un número de teléfono
    belongs_to :phone_type
    
    #validates_presence_of :num_telefono
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
end

app/models/reservation_car.rb
class ReservationCar < ActiveRecord::Base
end

app/models/service.rb
class Service < ActiveRecord::Base
    
    # Relaciones
    has_many :space_characteristics                                             # Un Servicio pertecene a muchas carecterísticas
    has_many :spaces, :dependent => :destroy, through: :space_characteristics   # Un Servicio pertecene a muchas espacios a travez de muchas características
    
    # Utilizando atributos de la Tabla Espacio y Espacio Características
    accepts_nested_attributes_for :space_characteristics
    accepts_nested_attributes_for :spaces
    
end

app/models/space.rb
class Space < ActiveRecord::Base
    
    # Un Espacio pertenece a un usuario
    belongs_to :user
    
     # Un espacio tiene un tipo de ofertante
    belongs_to :type_offer_person
    
    # Un espacio tiene un tipo de espacio
    belongs_to :space_type
    
    # Un espacio tiene una ubicacion
    has_one :space_ubication
    
    # Un Espacio tiene muchas carecterísticas
    has_many :space_characteristics, dependent: :destroy
    has_many :services, through: :space_characteristics
    
    # Utilizando atributos de la Tabla Espacio Ubicacion
    accepts_nested_attributes_for :space_ubication

end

app/models/space_type.rb
class SpaceType < ActiveRecord::Base
    
    # Un Tipo de Espacio tiene muchos Espacios
    has_many :spaces
    
end

app/models/space_ubication.rb
class SpaceUbication < ActiveRecord::Base
    
    # Una ubicación pertenece una ubicación
    belongs_to :space
    
    # Un País pertenece a un Perfil
    belongs_to :ub_country
    
    # Un Departamento pertenece a un Perfil
    belongs_to :ub_department
    
    # Una Provincia pertenece a un Perfil
    belongs_to :ub_province
    
    # Un Distrito pertenece a un Perfil
    belongs_to :ub_district
    
    # Utilizando atributos de otros modelos
    accepts_nested_attributes_for :ub_country
    accepts_nested_attributes_for :ub_department
    accepts_nested_attributes_for :ub_province
    accepts_nested_attributes_for :ub_district
    
end

app/models/ub_country.rb
class UbCountry < ActiveRecord::Base
    
    # Un Perfil tiene un departamento
    has_one :profiles
    
    has_one :space_ubications
    
    has_many :ub_departments
    
end

app/models/ub_department.rb
class UbDepartment < ActiveRecord::Base
    
    # Un Perfil tiene un departamento
    has_one :profiles
    
    has_one :space_ubications
    
end

app/models/ub_district.rb
class UbDistrict < ActiveRecord::Base
    
    belongs_to :ub_provinces
    
    belongs_to :ub_departments
    
    # Un Perfil tiene un Distrito
    has_one :profiles
    
    has_one :space_ubications
    
end

app/models/ub_province.rb
class UbProvince < ActiveRecord::Base
    
    belongs_to :ub_departments
    
    # Un Perfil tiene una provincia
    has_one :profiles
    
    has_one :space_ubications
    
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_one :profile  
  has_many :space  
  
  after_create :set_default_profile  
  
  # Definiendo por defecto que el modelo Usuario cree un nuevo objecto Perfil
  def set_default_profile   

    profile = Profile.new   
    profile.nombres = ''
    profile.user_id = self.id
    profile.save 
    
    # Numero de Celular
    profile_phone = ProfilePhone.new   
    profile_phone.num_telefono  = ''
    profile_phone.phone_type_id = 1 # Celular
    profile_phone.profile_id = profile.id 
    profile_phone.save
    
    # Numero de Telefono
    profile_phone1 = ProfilePhone.new   
    profile_phone1.num_telefono = ''
    profile_phone1.phone_type_id = 2 # Fijo
    profile_phone1.profile_id = profile.id 
    profile_phone1.save
      
  end
  
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/spaces_helper.rb
module SpacesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Instaparkingv1" %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
    <%= javascript_include_tag "application" %>
    <style>
      body {
        padding-top: 60px; 
      }  
    </style>
  </head>


  <body>

   <!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-responsive-collapse" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="<%= root_path %>">Instaparking</a>
        </div>  
        <div id="navbar" class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <%= render 'partials/menu' %>  
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <%= render 'partials/menu_right' %>  
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">
     <div class="row">

        <div class="col-lg-12">
          <!--<% if notice %>
            <p class="notice"><%= notice %></p>
          <% end %>-->
          
          <% if alert %>
            <p class="alert"><%= alert %></p>
          <% end %>
          <%= bootstrap_flash %>
          <%= yield %>
        </div>



      </div><!--/row-->
      <footer>
        <br>
        <p>&copy; Todos los Derechos Reservados 2016</p>
      </footer>
    </div> <!-- /container -->

  </body>
</html>

app/views/layouts/home_layout.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Instaparking" %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
		<script src="js/vendor/jquery.bxslider.min.js"></script>
		<script src="scripts/jquery.fancybox-1.3.4.js"></script>
    <%= javascript_include_tag "application" %>
    <style>
      body {
        padding-top: 60px; 
      }  
    </style>
  </head>
 
  <body>
    <!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-responsive-collapse" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="<%= root_path %>">Instaparking</a>
        </div>  
        <div id="navbar" class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <%= render 'partials/menu' %>  
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <%= render 'partials/menu_right' %>  
          </ul>
        </div>
      </div>
    </nav>
    
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <!--<% if notice %>
            <p class="notice"><%= notice %></p>
          <% end %>-->
          
          <% if alert %>
            <p class="alert"><%= alert %></p>
          <% end %>
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
       
      </div><!--/row-->
      <footer>
        <p>&copy; Todos los Derechos Reservados 2016</p>
      </footer>
    </div> <!-- /container -->
    
  </body>
</html>

app/views/layouts/profile_edit.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Instaparkingv1" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>


    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">InstaParking</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <%= render 'partials/menu' %>  
          </ul>
          <ul class="nav navbar-nav navbar-right">
              <%= render 'partials/menu_right' %>  
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <% if user_signed_in? %>
        <div class="col-lg-9">
        <% else %>  
        <div class="col-lg-12">
        <% end %>
          <!--<% if notice %>
            <p class="notice"><%= notice %></p>
          <% end %>-->
          
          <% if alert %>
            <p class="alert"><%= alert %></p>
          <% end %>
          
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <%= render 'partials/menu_user' %>  
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2016</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/layouts/spaces_layout.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Instaparkingv1" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
    
    <style>
      #map {
        
        height: 300px;
      }
    </style>
    
    <!--<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA9P73aj_uKJWCsTwxS-lq1SiE15ciWHDk&signed_in=true"></script>-->

  </head>
  <body>


    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">InstaParking</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <%= render 'partials/menu' %>  
          </ul>
          <ul class="nav navbar-nav navbar-right">
              <%= render 'partials/menu_right' %>  
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <% if user_signed_in? %>
        <div class="col-lg-9">
        <% else %>  
        <div class="col-lg-12">
        <% end %>
          <!--<% if notice %>
            <p class="notice"><%= notice %></p>
          <% end %>-->
          
          <% if alert %>
            <p class="alert"><%= alert %></p>
          <% end %>
          
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <%= render 'partials/menu_user' %>  
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2016</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/pages/about_us.html.erb
<div class="listing">

    <div class="page">

        <h1 class="page-title">SOBRE NOSOTROS</h1>
        <p>INSTAPARKING es el proveedor líder en lo que Alquiler de estacionamiento se refiere. A través de INSTAPARKING, los conductores planifican de forma más inteligente su reserva de estacionamiento garantizado de antemano. INSTAPARKING dota sus clientes de la capacidad de buscar y comparar miles de opciones de aparcamiento y precios en más de 40 ciudades en toda la capital. Los conductores pueden fácilmente reservar un lugar antes de tiempo en aparcamientos y garajes en su ciudad, o pueden reservar on-the-go con la aplicación móvil premiado de la compañía para iOS y Android.</p>

        <h2 id="missions">Misi&oacute;n</h2>

        <p>poner aqui la mision de la empresa</p>

        <h2 id="vissions">Visi&oacute;n</h2>

        <p>Poner aqui la vision.</p>

        <h2 id="about-the-site">Acerca del Sitio</h2>

        <p>Acerca del Sitio.</p>

    </div>

</div>

app/views/pages/contact_us.html.erb
<h1>Pages#contact_us</h1>
<p>Find me in app/views/pages/contact_us.html.erb</p>

app/views/pages/gracias.html.erb
    
    <div class="pp1">
          Gracias!
        </div>

        <div class="center2">
            <%= image_tag("logo_mail.png", :class => "logo_mail", :alt => "Gracias") %>
        </div>

        <div class="center">
          <%= link_to '<button type="button">Continuar</button>'.html_safe, root_path %>
        </div>
        
    <div class="pp2">Muy pronto estaremos en contacto contigo.</div>
        
       
        
  

app/views/partials/_menu.html.erb
<li><%= link_to "Nosotros", pages_about_us_path %></li>
<li><%= link_to "Preguntas Frecuentes", pages_faq_path  %></li>
<li><%= link_to "Terminos y Condiciones", pages_tos_path  %></li>
<li><%= link_to "Contactanos", new_contacto_path  %></li>

app/views/partials/_menu_right.html.erb
<% if user_signed_in? %>  
    <% if(current_user.profile.nombres != '') %> 
        <p class="navbar-text">Bienvenido: <%= link_to current_user.profile.nombres, controller: "profiles", action: "show", id: current_user.profile.id %></p>
    <% else %>
        <p class="navbar-text">Bienvenido: <%= link_to current_user.email, controller: "profiles", action: "show", id: current_user.profile.id %></p>
    <% end %>
    <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Configuraciones <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <!-- Aplicando Link para Mostrar perfil  -->        
          <li><%= link_to "Editar Perfil", controller: "profiles", action: "edit", id: current_user.profile.id %></li>
          <li><%= link_to "Cambiar Contrasena", edit_user_password_path %></li>
          <li><%= link_to "Cerrar Sesión", destroy_user_session_path, method: :delete  %></li>
        </ul>
    </li>
<% else %>
    <li><%= link_to "Iniciar sesión", new_user_session_path %></li>
    <li><%= link_to "Crear Cuenta", new_user_registration_path %></li>
<% end  %>

app/views/partials/_menu_user.html.erb
<% if user_signed_in? %>  
  <div class="col-lg-3">
    <div class="well sidebar-nav">
      <ul class="nav nav-list">
        <li class="nav-header">Menu Principal</li>
        <li><%= link_to "Crear Espacios", new_space_path %></li>
        <li><%= link_to 'Mis Espacios', controller: "spaces", action: "list", id: current_user.id %></li>
        <li><%= link_to 'Mis Reservas', controller: "spaces", action: "index" %></li>
        <li><%= link_to 'Reservar', controller: "spaces", action: "index" %></li>
        <li><%= link_to "Mis Favoritos", controller: "spaces", action: "index"  %></li>
      </ul>
    </div><!--/.well -->
  </div><!--/span-->
<% end %>